#!/usr/bin/env python3
"""
Enumerate every packed sub-file in Suikoden IV's FILEDATA archives (issue #44).

`FILEDATA.BI1` and `FILEDATA.BI2` are not single archives, which is what the notebook used to
say. Each is a run of back-to-back, self-describing archives:

    +0x00  u32  magic 0x82734927
    +0x04  u32  0
    +0x08  u32  total archive size (bytes, before sector padding)
    +0x0C  u32  0
    +0x10  16-byte entry rows (id u32, flags u32, offset u32, size u32)
           row[0] is a SENTINEL: its `id` field is the entry count, flags=32, off=0, size=0
           offsets are archive-relative and 16-byte aligned

The archives TILE their file exactly — every archive's `total`, rounded up to a 2048-byte
sector, lands on the next archive's header, with BI1's last archive ending on the file's final
byte. That is S3's FSECT.BIN test, and it passes here 258/258 and 1065/1065.

Because tiling is exact, the index does not need to scan a gigabyte for magic numbers: it WALKS
the chain from offset 0, reading each header's `total` and jumping. 1,326 small reads instead of
streaming 1.1 GB.

Reads a disc, writes JSON. The disc is never redistributed (CLAUDE.md rule 3) so a path is
required; the output index carries offsets and sizes only — no game content.

    python3 Editor/build_s4_subfile_index.py "Base ISO/Suikoden IV (USA).iso" -o Editor/s4_subfile_index.json
    python3 Editor/build_s4_subfile_index.py <iso> --verify      # tiling test only, no output

stdlib only.
"""
import argparse
import json
import struct
import sys

MAGIC = 0x82734927
SECTOR = 2048

# LBA and length from the ISO9660 table in Suikoden4_offsets.md. FILEDATA.BIN is deliberately
# absent: it is not an archive (it starts with a copy of SYSTEM.CNF text).
ARCHIVE_FILES = {
    "BI1": {"lba": 1510597, "size": 1074509824},
    "BI2": {"lba": 2035260, "size": 60162048},
}


def walk_archives(fh, base, size):
    """Yield (offset, total) for each archive, following the tiling chain from offset 0."""
    cur = 0
    while cur < size - 16:
        fh.seek(base + cur)
        head = fh.read(16)
        if len(head) < 16:
            return
        magic, _z1, total, _z2 = struct.unpack("<4I", head)
        if magic != MAGIC or total == 0:
            return
        yield cur, total
        step = (total + SECTOR - 1) // SECTOR * SECTOR
        if step == 0:
            return
        cur += step


def read_entries(fh, base, arc_off):
    """Entry rows of one archive, or None when the sentinel doesn't look like a count."""
    fh.seek(base + arc_off + 0x10)
    first = fh.read(16)
    if len(first) < 16:
        return None
    count = struct.unpack("<4I", first)[0]
    # A count of 0 is a legitimately EMPTY archive: total=2048 (header sector only) and every
    # row zero. 15 of BI1's 1,066 are like this. They were briefly recorded as "archives that
    # don't parse" (#45); they parse fine, there is just nothing in them.
    if count == 0:
        return []
    if count > 4000:
        return None                      # genuinely unreadable — a count this large is not one
    fh.seek(base + arc_off + 0x10)
    tbl = fh.read(16 * count)
    if len(tbl) < 16 * count:
        return None
    rows = [struct.unpack("<4I", tbl[i * 16:i * 16 + 16]) for i in range(count)]
    return [{"id": eid, "flags": fl, "off": off, "size": sz}
            for eid, fl, off, sz in rows[1:] if sz > 0]      # row[0] is the count sentinel


def build(iso_path, verify_only=False):
    out = {"_note": "Generated by Editor/build_s4_subfile_index.py — offsets and sizes only, no game content.",
           "files": {}}
    problems = []
    with open(iso_path, "rb") as fh:
        for name, meta in ARCHIVE_FILES.items():
            base, size = meta["lba"] * SECTOR, meta["size"]
            archives, tiles, pairs = [], 0, 0
            prev = None
            for arc_off, total in walk_archives(fh, base, size):
                if prev is not None:
                    pairs += 1
                    if (prev[1] + SECTOR - 1) // SECTOR * SECTOR == arc_off - prev[0]:
                        tiles += 1
                entries = read_entries(fh, base, arc_off)
                if entries is None:
                    problems.append(f"{name}: archive at {arc_off:#x} has no readable entry count")
                archives.append({"off": arc_off, "total": total,
                                 "entries": entries if entries is not None else []})
                prev = (arc_off, total)
            end = prev[0] + (prev[1] + SECTOR - 1) // SECTOR * SECTOR if prev else 0
            nent = sum(len(a["entries"]) for a in archives)
            out["files"][name] = {
                "lba": meta["lba"], "size": size,
                "archives": len(archives), "entries": nent,
                "tiling": {"ok": tiles, "of": pairs},
                "tailBytes": size - end,
                "archiveList": archives,
            }
            print(f"{name}: {len(archives)} archives, {nent} entries, "
                  f"tiling {tiles}/{pairs}, tail {size - end} bytes", file=sys.stderr)
    for p in problems:
        print("  ! " + p, file=sys.stderr)
    return out


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("iso")
    ap.add_argument("-o", "--out")
    ap.add_argument("--verify", action="store_true", help="report the tiling test and exit")
    a = ap.parse_args()
    idx = build(a.iso, a.verify)
    if a.verify:
        bad = [f"{k}: {v['tiling']['ok']}/{v['tiling']['of']}" for k, v in idx["files"].items()
               if v["tiling"]["ok"] != v["tiling"]["of"]]
        sys.exit(("tiling FAILED — " + "; ".join(bad)) if bad else 0)
    if a.out:
        # Summary only by default: the full archiveList is ~62k entries and would dwarf every
        # other committed table. --full writes it when someone actually needs it.
        slim = {"_note": idx["_note"],
                "files": {k: {kk: vv for kk, vv in v.items() if kk != "archiveList"}
                          for k, v in idx["files"].items()}}
        with open(a.out, "w", encoding="utf-8") as fh:
            json.dump(slim, fh, indent=1)
        print(f"wrote {a.out}", file=sys.stderr)
